### ISSUE TITLE
Troubles with `GamesDict` realization

### ISSUE THREAD

**Issue by D-Mantrid** [Discarded-Team/pyndemic-web-backend#4]
I think there are several issues in the current version of the `GamesDict` class.

1. Missed definition for `self.data` used in the class methods:
https://github.com/Discarded-Team/pyndemic-web-backend/blob/786d7a506c70c1868dd969334448f0fbba2d786e/src/game_managment.py#L20-L21

2. The `__getitem__` method totally replaces the method of the parent `dict` class and thus loses its benefits.
https://github.com/Discarded-Team/pyndemic-web-backend/blob/786d7a506c70c1868dd969334448f0fbba2d786e/src/game_managment.py#L24-L26

3. Due to overloaded `__getitem__`, there is no actual use of the `__missing__` method (which is used by default `dict.__getitem__` method). Also, the purpose of the method is violated (the method should return some value). Finally, it tries to call `self[name]` leading to the same overloaded `__getitem__` call that makes no sense.
https://github.com/Discarded-Team/pyndemic-web-backend/blob/786d7a506c70c1868dd969334448f0fbba2d786e/src/game_managment.py#L28-L32

After all, is it worth defining this class except from manual logging features? As an alternative, we could just use the standard dict object and call logging from the higher level functions.

**Comment by eugenyProchan** [comment]
1. self.data is an internal property of `UserDict`, actually it's simple dict for keeping data.
2. If we will logging in higher level functions, we will call logger in a different places with same message.

method `__missing__` really excess, but I think we could use one place for logging attempt get or set the controller to dict and we could to define one place for it.

What do you think about it?
